config/routes.rb
Todolist::Application.routes.draw do
  
  resources :lists do
    resources :tasks
  end

  match "lists/:list_id/tasks/:id/change_status" => "tasks#change_status", :as => "change_status_task"

  root :to => "lists#index"
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :title
  validates_presence_of (:title)
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :status, :title_task
  belongs_to :list
  validates :title_task, presence: true, uniqueness: true
  scope :incomplete, where(:status => false)
  scope :finished, where(:status => true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(params[:list])
    if @list.save
      redirect_to @list, notice: "List was created" 
    else
      flash[:alert] = "List wasn't created :("
      render action: "new"
    end
  end

  def index
    @lists = List.all
    respond_to do |format|
      format.html
    end
  end

  def show
    @list = List.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(params[:list])
      redirect_to @list, notice: "List was updated" 
    else
      flash[:alert] = "List wasn't updated :("
      render action: "edit"
    end
  end

  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      flash[:notice] = "List was destroyed successfully"
      respond_to do |format|
        format.html { redirect_to lists_path }
      end
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :find_list

  def create
  	@task = @list.tasks.build(params[:task])
  	if @task.save
	  respond_to do |format|
        format.html {redirect_to list_path(@list), :notice => "Your task was created :)"}
      end
  	else
  	  respond_to do |format|
	      format.html {redirect_to list_path(@list), :alert => "Your task couldn't be submitted. :("}
      end
  	end
  end

  def destroy
  	@task = Task.find(params[:id])	
  	if @task.destroy
  	  respond_to do |format|
        format.html {redirect_to list_path(@list), :notice => "Your task was destroy susscefully :)"}
      end  			
  	end
  end

  def change_status
    @task = Task.find(params[:id])
    (@task.status == true) ? @task.status = false : @task.status = true
    @task.save
    redirect_to @list 
  end

  private 

  def find_list
    @list = List.find(params[:list_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>..:List To Do:..</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class= "navbar navbar-fixed-top" >
      <div class="navbar-inner">
        <div class "contaniner">
          <%=link_to "List to do", root_path, class: "brand"%>  
          <ul class="nav">
            <li><%=link_to "All Lists" , root_path%></li>
          </ul>
        </div>
      </div>
    </div>
    <footer class= "navbar navbar-fixed-bottom">
      <div class="navbar-inner">
        <div class="container">
          <a href="http://www.koombea.com" class ="brand">&copy; Koombea 2012</a> 
        </div>
      </div>
    </footer>

    <div class="contaniner">
      <%if notice%>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <p class="notice"><%= notice %></p> 
        </div>
      <%end%>
      <%if alert%>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <p><%= alert %></p>
        </div>
      <%end%>
    </div>

    <div id="yield" class="container">
      <p><%= yield %></p>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%=simple_form_for(@list) do |f|%>
  <div class="well">
    <%= f.input :title %>
    <%= f.submit class: "btn btn-primary  " %>
  </div>
<%end%>

app/views/lists/edit.html.erb
<fieldset>
  <legend>Create List</legend>
	<div class= "form_list">
		<%= render 'form'%>
		<%=link_to "Back To All List", root_path, class: "btn"%>
	</div>
</fieldset>

app/views/lists/index.html.erb
<fieldset>
  <legend>Lists To Do</legend>
	<div class = "form_list">
		<%if @lists.size > 0 %>
			<%@lists.each do |list| %>
				<div class = "well">
				<h3><%=link_to list.title, list%></h3>
				<%=link_to "Edit title", edit_list_path(list), class: "btn"%>
				<%=link_to "Delete", list, method: :delete, data:{confirm: "Are you sure your want to delete this list?"}, class: "btn"%>
				</div>
			<%end%>
		<%else%>
			<div class = "well">
				<h3>You did not create a list</h3>
			</div>	
		<%end%>
	</div>
	<%=link_to "Create a new List", new_list_path, class: "btn btn-primary"%>
</fieldset>

app/views/lists/new.html.erb
<fieldset>
  <legend>Create List</legend>
	<div class= "form_list">
		<%= render 'form'%>
		<%=link_to "Back To All List", root_path, class: "btn"%>
	</div>
</fieldset> 

app/views/lists/show.html.erb
<div class="page-header">
	<h2> List To Do  "<%=@list.title%>" | <small><%=link_to "Edit title", edit_list_path%></small></h2>
</div>
<div class="row">
	<div class = "span6">
		<fieldset>	
			<legend>Incomplete Tasks</legend>
			<div class="well" id="incomplete_tasks">
				<% if @list.tasks.incomplete.size > 0%>  
			  	<%@list.tasks.incomplete.each do |task|%>
						<p><li>
						<%=task.title_task%> | <%= link_to "Finished", change_status_task_path(@list.id, task), class: "btn btn-small" %> | <%= link_to "Delete", list_task_path(@list.id, task), method: :delete, data:{confirm: "Are you sure your want to delete this task?"} %></li></p>
					<%end%>
				<%else%>
			  	<p>This list does not have any incomplete task.</p>
				<%end%>
			</div>
			<legend>Finished Tasks</legend>
			<div class="well" id="finished_tasks">
				<% if @list.tasks.finished.size > 0%>  
			  	<% @list.tasks.finished.each do |task|%>
						<p><li><%=task.title_task%> | <%= link_to "No Finished", change_status_task_path(@list.id, task), class: "btn btn-small" %> | <%= link_to "Delete", list_task_path(@list.id, task), method: :delete, data:{confirm: "Are you sure your want to delete this task?"} %></li></p>
					<%end%>
				<%else%>
			  	<p>This list does not have any finished task.</p>
				<%end%>
			</div>
		</fieldset>
	</div>
	<div class = "span6">
		<legend>New Task</legend>
		<p><%=render "task/form"%></p>
		<p><%=link_to "Back To All List", root_path, class: "btn"%></p>
		<input style="width:100%" readonly="readonly" value="<iframe src='<%=list_url(@list)%>' width='945' height='550'></iframe>" ></input>
	</div>			
</div>

app/views/task/_form.html.erb
<%=simple_form_for([@list, @list.tasks.build]) do |f|%>
  <div class="well" id="task_form">
    <%= f.input :title_task %>
    <%= f.submit class: "btn btn-primary  " %>
  </div>
<%end%>

app/views/tasks/_task.html.erb
<div class = "well">
  <b><%="#{task.title_task}"%></b>
  <p><%= task.status%></p>
  <%=link_to "Delete task", list_task_path(task.list, task), method: :delete, data:{confirm: "Are you sure your want to delete this task?"}%>
</div>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>